name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [21]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.6.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Cache Gradle files
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle

      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew chiseledBuild

      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Artifacts
          path: |
            build/libs/
            CHANGELOG.md


  publish:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # TODO: Update game versions to match mod compatibility
        game_version: [
          "1.19-1.19.2",
          "1.19.3-1.19.4",
          "1.20-1.20.1",
          "1.20.2-1.20.4",
          "1.20.5",
          "1.20.6",
          "1.21-1.21.3",
          "1.21.4"
        ]

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: Artifacts
          path: ./

      - name: Extract mod version
        id: extract_version
        run: |
          # Save the first found file to a variable
          file=$(ls ./build/libs/keep-xp-* | head -n 1)
          mod_version=$(basename "$file" | sed -E 's/keep-xp-([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          
          # Save the mod version to the environment
          echo "mod_version=$mod_version" >> $GITHUB_ENV
          echo "Extracted mod version: $mod_version"

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          fail-mode: warn
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          changelog-file: ./CHANGELOG.md
          files: ./build/libs/keep-xp-*+${{ matrix.game_version }}.jar
          name: Keep XP ${{ matrix.game_version }} v${{ env.mod_version }}

      - name: Publish to Github
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          fail-mode: warn
          github-token: ${{ secrets.GIT_TOKEN }}

          changelog-file: ./CHANGELOG.md
          files: ./build/libs/keep-xp-*+${{ matrix.game_version }}.jar
          name: Keep XP v${{ env.mod_version }}